package com.github.ogyct.pdfpasswordremover.gui;

import javax.swing.JFrame;
import javax.swing.JButton;
import javax.swing.JTextField;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JPasswordField;
import javax.swing.JLabel;
import java.awt.Component;
import java.awt.ComponentOrientation;

/**
 * Gui(view) implementation
 * @author avgustisd
 *
 */
public class GUI {

    private static final String REMOVE_PASSWORDS = "Remove passwrods";
    private static final String PDF_PASSWORD_REMOVER = "PDF Password Remover";
    private JFrame frmPdfPasswordRemover;

    public JFrame getFrmPdfPasswordRemover() {
        return frmPdfPasswordRemover;
    }

    public void setFrmPdfPasswordRemover(JFrame frmPdfPasswordRemover) {
        this.frmPdfPasswordRemover = frmPdfPasswordRemover;
    }

    public JTextField getTextField() {
        return textField;
    }

    public void setTextField(JTextField textField) {
        this.textField = textField;
    }

    public JButton getBtnRemove() {
        return btnRemove;
    }

    public void setBtnRemove(JButton btnRemove) {
        this.btnRemove = btnRemove;
    }

    public JButton getBtnChoose() {
        return btnChoose;
    }

    public void setBtnChoose(JButton btnChoose) {
        this.btnChoose = btnChoose;
    }

    private JTextField textField;
    private JButton btnRemove;
    private JButton btnChoose;
    private JPasswordField passwordField;

    /**
     * Create the application.
     */
    public GUI() {
        initialize();
    }

    /**
     * Initialize the contents of the frame.
     * Generated by window builder
     */
    private void initialize() {
        frmPdfPasswordRemover = new JFrame();
        frmPdfPasswordRemover.getContentPane().setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
        frmPdfPasswordRemover.setResizable(false);
        frmPdfPasswordRemover.setTitle(PDF_PASSWORD_REMOVER);

        frmPdfPasswordRemover.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        textField = new JTextField();
        textField.setText(".");
        textField.setAlignmentX(Component.LEFT_ALIGNMENT);
        textField.setToolTipText("Path");
        textField.setColumns(20);

        btnRemove = new JButton(REMOVE_PASSWORDS);
        btnRemove.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
        btnRemove.setAlignmentY(Component.TOP_ALIGNMENT);

        btnChoose = new JButton("Choose Directory");

        passwordField = new JPasswordField();
        passwordField.setAlignmentX(Component.LEFT_ALIGNMENT);
        passwordField.setToolTipText("Password");

        JLabel pathLabel = new JLabel("Path");

        JLabel passwordLabel = new JLabel("Password");
        GroupLayout groupLayout = new GroupLayout(frmPdfPasswordRemover.getContentPane());
        groupLayout.setHorizontalGroup(
            groupLayout.createParallelGroup(Alignment.TRAILING)
                .addGroup(groupLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                        .addComponent(pathLabel)
                        .addComponent(passwordLabel))
                    .addGap(4)
                    .addGroup(groupLayout.createParallelGroup(Alignment.TRAILING, false)
                        .addComponent(textField, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 175, GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordField, GroupLayout.PREFERRED_SIZE, 175, GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                        .addGroup(groupLayout.createSequentialGroup()
                            .addComponent(btnChoose, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(10))
                        .addGroup(groupLayout.createSequentialGroup()
                            .addComponent(btnRemove, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(10)))
                    .addContainerGap())
        );
        groupLayout.setVerticalGroup(
            groupLayout.createParallelGroup(Alignment.LEADING)
                .addGroup(groupLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(pathLabel)
                        .addComponent(btnChoose))
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(passwordField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordLabel)
                        .addComponent(btnRemove))
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frmPdfPasswordRemover.getContentPane().setLayout(groupLayout);
        frmPdfPasswordRemover.pack();
    }

    public JPasswordField getPasswordField() {
        return passwordField;
    }

    public void setPasswordField(JPasswordField passwordField) {
        this.passwordField = passwordField;
    }
}
